// <auto-generated />
using System;
using BlogSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogSystem.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogSystem.API.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("BlogSystem.API.Models.ContactoForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ContactoForm");
                });

            modelBuilder.Entity("BlogSystem.API.Models.ExcedenteEnergiaEnFuncionamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlquilarParteOTotalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Autoconsumo")
                        .HasColumnType("bit");

                    b.Property<int>("CapacidadProduccion")
                        .HasColumnType("int");

                    b.Property<int>("CapacidadProduccionEnergia")
                        .HasColumnType("int");

                    b.Property<int?>("CapacidadProduccionLicencia")
                        .HasColumnType("int");

                    b.Property<string>("Coordenadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiasExcedenteEnergia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ExcedenteEnergia")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaInicioProduccion")
                        .HasColumnType("date");

                    b.Property<string>("HorasExcedenteEnergia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MunicipioInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtrasTecnologias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProduceEnergia")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinciaInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuiereProducirConExcedente")
                        .HasColumnType("bit");

                    b.Property<bool>("TieneLicencia")
                        .HasColumnType("bit");

                    b.Property<string>("TipoTecnologia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VierteEnergiaRed")
                        .HasColumnType("bit");

                    b.Property<int?>("VierteEnergiaTrue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExcedentesEnergiaEnFuncionamiento");
                });

            modelBuilder.Entity("BlogSystem.API.Models.ExcedenteEnergiaNuevo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlquilarInstalaciones")
                        .HasColumnType("bit");

                    b.Property<int?>("AnosAlquiler")
                        .HasColumnType("int");

                    b.Property<int?>("CapacidadProduccionLicencia")
                        .HasColumnType("int");

                    b.Property<string>("Coordenadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DestinaInstalacion")
                        .HasColumnType("bit");

                    b.Property<bool>("InstalacionConstruida")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("InstalacionContruidaFalse")
                        .HasColumnType("date");

                    b.Property<bool>("InstalacionEnConstruccion")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("InstalacionEnConstruccionTrue")
                        .HasColumnType("date");

                    b.Property<int?>("KwDestinados")
                        .HasColumnType("int");

                    b.Property<int?>("KwTotalesProduccion")
                        .HasColumnType("int");

                    b.Property<string>("MunicipioInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroHoras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtrasTecnologias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuierePersonalTramitar")
                        .HasColumnType("bit");

                    b.Property<bool>("QuiereProducirConExcedente")
                        .HasColumnType("bit");

                    b.Property<bool>("TieneLicencia")
                        .HasColumnType("bit");

                    b.Property<string>("TipoTecnologia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExcedentesEnergiaNuevo");
                });

            modelBuilder.Entity("BlogSystem.API.Models.ProduccionHidrogeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlquilarTerrenoConInstalaciones")
                        .HasColumnType("bit");

                    b.Property<bool>("AlquilarTerrenoSinInstalaciones")
                        .HasColumnType("bit");

                    b.Property<int>("AnosAlquiler")
                        .HasColumnType("int");

                    b.Property<bool>("Autoconsumo")
                        .HasColumnType("bit");

                    b.Property<bool>("AyudaProveedorPPA")
                        .HasColumnType("bit");

                    b.Property<int>("BaresHidrogeno")
                        .HasColumnType("int");

                    b.Property<bool>("ContratarPPA")
                        .HasColumnType("bit");

                    b.Property<int>("CuantoKiloGramosHora")
                        .HasColumnType("int");

                    b.Property<string>("DistribucionSelect")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EquiposAlmacenar")
                        .HasColumnType("bit");

                    b.Property<bool>("EquiposProducir")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("FechaHidrogenoDisponible")
                        .HasColumnType("date");

                    b.Property<string>("IndicarCual")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IndustrialSelect")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("InstalacionConstruida")
                        .HasColumnType("bit");

                    b.Property<bool>("MetanolVerde")
                        .HasColumnType("bit");

                    b.Property<string>("MovilidadSelect")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MunicipioConsumicion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MunicipioNecesita")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MunicipioProduccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NecesitaEmpresa")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("OtraTecnologia")
                        .HasColumnType("bit");

                    b.Property<string>("OtrasTecnologias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OtrasTecnologiasAlquiler")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OtroSector")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaisConsumicion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaisNecesita")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaisProduccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ProporcionClientes")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinciaConsumicion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProvinciaNecesita")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProvinciaProduccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RedEmpresas")
                        .HasColumnType("bit");

                    b.Property<bool>("RedHidrogeneras")
                        .HasColumnType("bit");

                    b.Property<bool>("RedPuntosDispensacion")
                        .HasColumnType("bit");

                    b.Property<string>("ResidencialSelect")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoSectorProduccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTecnologia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTecnologiaAlquiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TramitacionSolicitudes")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ProduccionesHidrogeno");
                });

            modelBuilder.Entity("BlogSystem.API.Models.TransporteHidrogeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FalseLicenciaAsesoramiento")
                        .HasColumnType("bit");

                    b.Property<bool>("LicenciaMercanciaPeligrosa")
                        .HasColumnType("bit");

                    b.Property<string>("MunicipioTransporte")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NecesitaFormacion")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisTransporte")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PresionHidrogeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaTransporte")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RedTransporte")
                        .HasColumnType("bit");

                    b.Property<bool>("TieneCaminonesHidrogeno")
                        .HasColumnType("bit");

                    b.Property<bool>("TieneCamionesAmoniaco")
                        .HasColumnType("bit");

                    b.Property<bool>("TieneCamionesMetanol")
                        .HasColumnType("bit");

                    b.Property<string>("TipoRed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTransporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTransporteHidrogeno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransportesHidrogeno");
                });

            modelBuilder.Entity("BlogSystem.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidosRepresentante")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CIF")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DNI")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreRepresentante")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Representante")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoEntidad")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlogSystem.API.Models.VendeAlquilaHidrogeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnosAlquiler")
                        .HasColumnType("int");

                    b.Property<string>("Coordenadas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Licencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MetrosCuadradosTerreno")
                        .HasColumnType("int");

                    b.Property<string>("MunicipioAlVen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisAlVen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrecioAlquiler")
                        .HasColumnType("int");

                    b.Property<int>("PrecioVenta")
                        .HasColumnType("int");

                    b.Property<string>("ProvinciaAlVen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TieneLicencia")
                        .HasColumnType("bit");

                    b.Property<string>("TipoTerreno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenderAlquilar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VentaAlquilerHidrogeno");
                });

            modelBuilder.Entity("BlogSystem.API.Models.BlogPost", b =>
                {
                    b.HasOne("BlogSystem.API.Models.User", "User")
                        .WithMany("BlogPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogSystem.API.Models.User", b =>
                {
                    b.Navigation("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
